#!/bin/bash

#----------------------------------------------------------------------------
# Install OpenLDAP on the controller node
#----------------------------------------------------------------------------
yum -y install openldap openldap-clients openldap-servers
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
chkconfig slapd on
service slapd start

ldapmodify -Y EXTERNAL -H ldapi:/// << EOF
dn: olcDatabase={2}hdb,cn=config
changetype: modify
add: olcRootPW
olcRootPW: system
-
replace: olcSuffix
olcSuffix: dc=cluster
-
replace: olcRootDN
olcRootDN: cn=Manager,dc=cluster
EOF

#----------------------------------------------------------------------------
# Install the required schema's + custom one for the uid
#----------------------------------------------------------------------------
slapadd -n 0  -l /etc/openldap/schema/cosine.ldif
slapadd -n 0  -l /etc/openldap/schema/nis.ldif
slapadd -n 0  -l /etc/openldap/schema/inetorgperson.ldif

cat > /tmp/trinity.ldif << EOF
dn: cn=trinity,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: trinity
olcObjectClasses: {0}( 1.3.6.1.4.1.19173.2.2.2.8
 NAME 'uidNext'
 DESC 'Where we get the next uidNumber from'
 MUST ( cn $ uidNumber ) )
EOF

slapadd -n 0  -l /tmp/trinity.ldif

chown ldap:ldap /etc/openldap/slapd.d/cn\=config/cn\=schema/*
systemctl restart slapd

#----------------------------------------------------------------------------
# Setup the initial database
#----------------------------------------------------------------------------
ldapadd -D cn=Manager,dc=cluster -w system << EOF
dn: dc=cluster
dc: cluster
objectClass: domain

dn: ou=People,dc=cluster
ou: People
objectClass: top
objectClass: organizationalUnit

dn: ou=Group,dc=cluster
ou: Group
objectClass: top
objectClass: organizationalUnit

dn: cn=uid,dc=cluster
cn: uid
objectClass: uidNext
uidNumber: 1050
EOF

#----------------------------------------------------------------------------
# Change access rights to allow for PAM users to authenticate
#----------------------------------------------------------------------------
ldapmodify -Y EXTERNAL -H ldapi:/// << EOF
dn: olcDatabase={2}hdb,cn=config
changetype: modify
add: olcAccess
olcAccess: to attrs=userPassword by self write 
                                 by anonymous auth 
                                 by * none
- 
add: olcAccess
olcAccess: to * by self write 
                by * read
EOF

#----------------------------------------------------------------------------
# Setup PAM
#----------------------------------------------------------------------------
yum -y install nss-pam-ldapd authconfig

# append our config to the ldap nameserver demon
cat >> /etc/nslcd.conf << EOF 
uri ldap://localhost
ssl no
tls_cacertdir /etc/openldap/cacerts
base   group  ou=Group,dc=cluster
base   passwd ou=People,dc=cluster
base   shadow ou=People,dc=cluster
EOF

# configure the ldap server. Not sure this is needed.
cat >> /etc/pam_ldap.conf << EOF
uri ldap://localhost/
base dc=cluster
ssl no
tls_cacertdir /etc/openldap/cacerts
pam_password md5
EOF

# setup nssswitch
sed -e 's/^group:.*$/group:\t\tfiles ldap/g' \
    -e 's/^passwd:.*$/passwd:\t\tfiles ldap/g' \
    -e 's/^shadow:.*$/shadow:\t\tfiles ldap/g' \
    -i /etc/nsswitch.conf 

authconfig-tui --kickstart --enableldapauth --ldapbasedn=dc=cluster \
     --ldapserver=localhost

echo "slapd installed" >> /var/log/postinstall.log

exit 0

