#!/bin/bash
#--------------------------------------------------------------------------------------
# install docker and docker-registry
# and create the trinity image for the compute nodes
#--------------------------------------------------------------------------------------
yum -y install docker docker-registry
sed -i 's/REGISTRY_PORT=.*/REGISTRY_PORT=5050/' /etc/sysconfig/docker-registry
sed -i 's/OPTIONS=\(.*\)/OPTIONS=--insecure-registry controller:5050 \1/' /etc/sysconfig/docker
echo "10.141.255.254 controller" >>  /etc/hosts
systemctl enable docker docker-registry
systemctl start docker docker-registry
docker build -t controller:5050/trinity /trinity/compute
docker push controller:5050/trinity

echo "docker installed" >> /var/log/postinstall.log

