#!/bin/sh

#--------------------------------------------------------------------------------------
# install xcat
#--------------------------------------------------------------------------------------
yum -y install xCAT

#--------------------------------------------------------------------------------------
# install module environments
#--------------------------------------------------------------------------------------
# HTH: Not required on xCAT controller (only in login node)
# HTH: yum -y install environment-modules
mkdir /tmp/trinity
mount controller:/home/trinity /tmp/trinity
mkdir /trinity

# copy all required module files etc to the right locations
# note to self: only /trinity/env needs be mounted inside the container
cp -r /tmp/trinity/env /trinity

# also copy the files we want to distribute into the compute images
cp -r /tmp/trinity/compute /trinity

# HTH: not needed, since we only use these when installing the controller
# HTH: cp -r /tmp/trinity/controller /trinity

#--------------------------------------------------------------------------------------
# enable all repositories inside the controller
#--------------------------------------------------------------------------------------
cd /etc/yum.repos.d
for file in * ; do sed -i 's/enabled=0/enabled=1/g' $file; done
cd -

#--------------------------------------------------------------------------------------
# copy required files from the master node to the controller node
#--------------------------------------------------------------------------------------
cp -r /tmp/trinity/controller/* /

#--------------------------------------------------------------------------------------
# copy default database configuration
#--------------------------------------------------------------------------------------
restorexCATdb -p /tmp/trinity/xcat/tables

#--------------------------------------------------------------------------------------
# now setup NFS
#--------------------------------------------------------------------------------------
yum -y install nfs-utils nfs-utils-lib
systemctl enable nfs
systemctl start nfs

cat << END > /etc/exports 
/tftpboot *(rw,no_root_squash,sync,no_subtree_check)
/install *(rw,no_root_squash,sync,no_subtree_check)
/trinity *(rw,sync,no_root_squash,no_all_squash)
/cluster *(rw,sync,no_root_squash,no_all_squash)
/home *(rw,sync,no_root_squash,no_all_squash)
END

exportfs -a

#--------------------------------------------------------------------------------------
# install docker and docker-registry
# and create the trinity image for the compute nodes
#--------------------------------------------------------------------------------------
yum -y install docker docker-registry
sed -i 's/REGISTRY_PORT=.*/REGISTRY_PORT=5050/' /etc/sysconfig/docker-registry
systemctl enable docker docker-registry
systemctl start docker docker-registry
docker build -t controller:5050/trinity /trinity/compute
docker push controller:5050/trinity

#--------------------------------------------------------------------------------------
# cleanup
#--------------------------------------------------------------------------------------
umount /tmp/trinity
rmdir /tmp/trinity

exit 0

