#!/bin/bash

# see http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
#exec > >(tee /var/log/postinstall.log)
#exec 2>&1

#--------------------------------------------------------------------------------------
# install xcat
#--------------------------------------------------------------------------------------
# HTH: added to make sure the network is up
sleep 10

ls /etc/yum.repos.d 
yum repolist
yum -y install xCAT 

mkdir /tmp/trinity
mount master:/trinity /tmp/trinity       
mkdir /trinity

# copy all required module files etc to the right locations
# note to self: only /trinity/env needs be mounted inside the container
# FIXME: this takes an awful amount of time
cp -r /tmp/trinity/clustervision /trinity

# copy the files we want to distribute into the compute images
cp -r /tmp/trinity/compute /trinity 

# HTH: not needed, since we only use these when installing the controller
# HTH: cp -r /tmp/trinity/controller /trinity

#--------------------------------------------------------------------------------------
# enable all repositories inside the controller
# but disable the local repo from master
#--------------------------------------------------------------------------------------
cd /etc/yum.repos.d
for file in * ; do sed -i 's/enabled=0/enabled=1/g' $file; done
sed -i 's/enabled=1/enabled=0/g' local-repository.repo
cd -

#--------------------------------------------------------------------------------------
# copy required files from the master node to the controller node
#--------------------------------------------------------------------------------------
cp -r /tmp/trinity/controller/* / 

#--------------------------------------------------------------------------------------
# copy default database configuration
# and patch the installation
#--------------------------------------------------------------------------------------
source /etc/profile.d/xcat.sh
restorexCATdb -p /tmp/trinity/xcat/tables  

cd /opt/xcat/share/xcat/netboot/centos
ln -s ../rh/dracut_033 .
ln -s ../rh/dracut .

cd /
cat /tmp/trinity/xcat/patches/*.patch | patch -p0

#--------------------------------------------------------------------------------------
# now setup NFS
#--------------------------------------------------------------------------------------
yum -y install nfs-utils nfs-utils-lib
systemctl enable nfs-server
systemctl start nfs-server

cat << END > /etc/exports 
/tftpboot *(rw,no_root_squash,sync,no_subtree_check)
/install *(rw,no_root_squash,sync,no_subtree_check)
/trinity *(rw,sync,no_root_squash,no_all_squash)
/cluster *(rw,sync,no_root_squash,no_all_squash)
/home *(rw,sync,no_root_squash,no_all_squash)
END

mkdir /cluster
exportfs -a

#--------------------------------------------------------------------------------------
# Create installation tree
#--------------------------------------------------------------------------------------
copycds /tmp/trinity/iso/*.iso
genimage -o centos7.0 -a x86_64 -p trinity -i ' '

echo "xcat installed" >> /var/log/postinstall.log
#--------------------------------------------------------------------------------------
# cleanup
#--------------------------------------------------------------------------------------
umount /tmp/trinity
rmdir /tmp/trinity

exit 0

